// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vaultaffe.Infrastructure.Persistence;

#nullable disable

namespace Vaultaffe.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VaultaffeDbContext))]
    [Migration("20260906200927_InstanceClaim")]
    partial class InstanceClaim
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vaultaffe.Domain.Environments.Environment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_environment");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_environment_project_name");

                    b.ToTable("environment", null, t =>
                        {
                            t.HasCheckConstraint("ck_environment_name", "name ~ '^[a-z0-9](?:[a-z0-9._-]*[a-z0-9])?$'");
                        });
                });

            modelBuilder.Entity("Vaultaffe.Domain.History.ChangeLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<string>("EnvironmentName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("environment_name");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<string>("IdentityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("identity_name");

                    b.Property<int>("IdentityType")
                        .HasColumnType("integer")
                        .HasColumnName("identity_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("project_name");

                    b.Property<string>("SecretName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("secret_name");

                    b.HasKey("Id")
                        .HasName("pk_change_log_entry");

                    b.HasIndex("OrganizationId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_change_log_entry_organization_occurred_at");

                    b.ToTable("change_log_entry", null, t =>
                        {
                            t.HasCheckConstraint("ck_change_log_entry_identity_type", "identity_type between 1 and 3");
                        });
                });

            modelBuilder.Entity("Vaultaffe.Domain.History.SecretAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("FirstAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_at");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<string>("IdentityName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("identity_name");

                    b.Property<int>("IdentityType")
                        .HasColumnType("integer")
                        .HasColumnName("identity_type");

                    b.Property<DateTimeOffset>("LastAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("SecretId")
                        .HasColumnType("uuid")
                        .HasColumnName("secret_id");

                    b.HasKey("Id")
                        .HasName("pk_secret_access");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("SecretId", "IdentityId")
                        .IsUnique()
                        .HasDatabaseName("ux_secret_access_secret_identity");

                    b.ToTable("secret_access", null, t =>
                        {
                            t.HasCheckConstraint("ck_secret_access_order", "last_at >= first_at");
                        });
                });

            modelBuilder.Entity("Vaultaffe.Domain.Identities.DeviceAuthorization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeniedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("denied_at");

                    b.Property<byte[]>("DeviceCodeHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("device_code_hash");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("IssuedTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_token_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("user_code");

                    b.HasKey("Id")
                        .HasName("pk_device_authorization");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("DeviceCodeHash")
                        .IsUnique()
                        .HasDatabaseName("ux_device_authorization_device_code_hash");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_device_authorization_expires_at");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UserCode")
                        .IsUnique()
                        .HasDatabaseName("ux_device_authorization_user_code");

                    b.ToTable("device_authorization", (string)null);
                });

            modelBuilder.Entity("Vaultaffe.Domain.Identities.InstanceClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("secret");

                    b.HasKey("Id")
                        .HasName("pk_instance_claim");

                    b.ToTable("instance_claim", (string)null);
                });

            modelBuilder.Entity("Vaultaffe.Domain.Identities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_by_user_id");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_user_id");

                    b.Property<bool>("IsAdministrator")
                        .HasColumnType("boolean")
                        .HasColumnName("is_administrator");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_at");

                    b.HasKey("Id")
                        .HasName("pk_invitation");

                    b.HasIndex("CodeHash")
                        .IsUnique()
                        .HasDatabaseName("ux_invitation_code_hash");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_invitation_email");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("invitation", null, t =>
                        {
                            t.HasCheckConstraint("ck_invitation_email", "email ~ '^[^@\\s]+@[^@\\s]+$'");
                        });
                });

            modelBuilder.Entity("Vaultaffe.Domain.Identities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdministrator")
                        .HasColumnType("boolean")
                        .HasColumnName("is_administrator");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_user_email");

                    b.HasIndex("OrganizationId");

                    b.ToTable("app_user", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_email", "email ~ '^[^@\\s]+@[^@\\s]+$'");
                        });
                });

            modelBuilder.Entity("Vaultaffe.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_organization");

                    b.ToTable("organization", (string)null);
                });

            modelBuilder.Entity("Vaultaffe.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_project");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_project_organization_name");

                    b.ToTable("project", null, t =>
                        {
                            t.HasCheckConstraint("ck_project_name", "name ~ '^[a-z0-9](?:[a-z0-9._-]*[a-z0-9])?$'");
                        });
                });

            modelBuilder.Entity("Vaultaffe.Domain.Secrets.DismissedKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DismissedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dismissed_at");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_dismissed_key");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("EnvironmentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_dismissed_key_environment_name");

                    b.ToTable("dismissed_key", null, t =>
                        {
                            t.HasCheckConstraint("ck_dismissed_key_name", "name ~ '^[A-Z_][A-Z0-9_]*$'");
                        });
                });

            modelBuilder.Entity("Vaultaffe.Domain.Secrets.Secret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Ciphertext")
                        .HasColumnType("bytea")
                        .HasColumnName("ciphertext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<byte[]>("Nonce")
                        .HasColumnType("bytea")
                        .HasColumnName("nonce");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("ValueWrittenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("value_written_at");

                    b.Property<byte[]>("WrappedDataKey")
                        .HasColumnType("bytea")
                        .HasColumnName("wrapped_data_key");

                    b.HasKey("Id")
                        .HasName("pk_secret");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("EnvironmentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_secret_environment_name");

                    b.ToTable("secret", null, t =>
                        {
                            t.HasCheckConstraint("ck_secret_name", "name ~ '^[A-Z_][A-Z0-9_]*$'");

                            t.HasCheckConstraint("ck_secret_value_sealed_whole", "(ciphertext is null and nonce is null and value_written_at is null)\nor (ciphertext is not null and nonce is not null\n    and value_written_at is not null and wrapped_data_key is not null)");
                        });
                });

            modelBuilder.Entity("Vaultaffe.Domain.Secrets.SecretValueVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("ciphertext");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("nonce");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("ReplacedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("replaced_at");

                    b.Property<Guid>("SecretId")
                        .HasColumnType("uuid")
                        .HasColumnName("secret_id");

                    b.Property<DateTimeOffset>("WrittenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("written_at");

                    b.HasKey("Id")
                        .HasName("pk_secret_value_version");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("SecretId", "ReplacedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_secret_value_version_secret_replaced_at");

                    b.ToTable("secret_value_version", (string)null);
                });

            modelBuilder.Entity("Vaultaffe.Domain.Tokens.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<int>("Scopes")
                        .HasColumnType("integer")
                        .HasColumnName("scopes");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<byte[]>("ValueHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("value_hash");

                    b.HasKey("Id")
                        .HasName("pk_token");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_token_user");

                    b.HasIndex("ValueHash")
                        .IsUnique()
                        .HasDatabaseName("ux_token_value_hash");

                    b.ToTable("token", null, t =>
                        {
                            t.HasCheckConstraint("ck_token_kind", "kind between 1 and 3");
                        });
                });

            modelBuilder.Entity("Vaultaffe.Domain.Tokens.TokenBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("token_id");

                    b.HasKey("Id")
                        .HasName("pk_token_binding");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TokenId", "ProjectId", "EnvironmentId")
                        .IsUnique()
                        .HasDatabaseName("ux_token_binding_token_project_environment");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("TokenId", "ProjectId", "EnvironmentId"), false);

                    b.ToTable("token_binding", (string)null);
                });

            modelBuilder.Entity("Vaultaffe.Domain.Environments.Environment", b =>
                {
                    b.HasOne("Vaultaffe.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_environment_organization");

                    b.HasOne("Vaultaffe.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_environment_project");
                });

            modelBuilder.Entity("Vaultaffe.Domain.History.SecretAccess", b =>
                {
                    b.HasOne("Vaultaffe.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_secret_access_organization");

                    b.HasOne("Vaultaffe.Domain.Secrets.Secret", null)
                        .WithMany()
                        .HasForeignKey("SecretId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_secret_access_secret");
                });

            modelBuilder.Entity("Vaultaffe.Domain.Identities.DeviceAuthorization", b =>
                {
                    b.HasOne("Vaultaffe.Domain.Identities.User", null)
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_device_authorization_approved_by");

                    b.HasOne("Vaultaffe.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_device_authorization_organization");
                });

            modelBuilder.Entity("Vaultaffe.Domain.Identities.Invitation", b =>
                {
                    b.HasOne("Vaultaffe.Domain.Identities.User", null)
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitation_invited_by");

                    b.HasOne("Vaultaffe.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitation_organization");
                });

            modelBuilder.Entity("Vaultaffe.Domain.Identities.User", b =>
                {
                    b.HasOne("Vaultaffe.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_organization");
                });

            modelBuilder.Entity("Vaultaffe.Domain.Projects.Project", b =>
                {
                    b.HasOne("Vaultaffe.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_organization");
                });

            modelBuilder.Entity("Vaultaffe.Domain.Secrets.DismissedKey", b =>
                {
                    b.HasOne("Vaultaffe.Domain.Environments.Environment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dismissed_key_environment");

                    b.HasOne("Vaultaffe.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dismissed_key_organization");
                });

            modelBuilder.Entity("Vaultaffe.Domain.Secrets.Secret", b =>
                {
                    b.HasOne("Vaultaffe.Domain.Environments.Environment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_secret_environment");

                    b.HasOne("Vaultaffe.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_secret_organization");
                });

            modelBuilder.Entity("Vaultaffe.Domain.Secrets.SecretValueVersion", b =>
                {
                    b.HasOne("Vaultaffe.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_secret_value_version_organization");

                    b.HasOne("Vaultaffe.Domain.Secrets.Secret", null)
                        .WithMany()
                        .HasForeignKey("SecretId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_secret_value_version_secret");
                });

            modelBuilder.Entity("Vaultaffe.Domain.Tokens.Token", b =>
                {
                    b.HasOne("Vaultaffe.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_token_organization");

                    b.HasOne("Vaultaffe.Domain.Identities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_token_user");
                });

            modelBuilder.Entity("Vaultaffe.Domain.Tokens.TokenBinding", b =>
                {
                    b.HasOne("Vaultaffe.Domain.Environments.Environment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_token_binding_environment");

                    b.HasOne("Vaultaffe.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_token_binding_organization");

                    b.HasOne("Vaultaffe.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_token_binding_project");

                    b.HasOne("Vaultaffe.Domain.Tokens.Token", null)
                        .WithMany("Bindings")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_token_binding_token");
                });

            modelBuilder.Entity("Vaultaffe.Domain.Tokens.Token", b =>
                {
                    b.Navigation("Bindings");
                });
#pragma warning restore 612, 618
        }
    }
}
